---
# Развёртывание Ansible Semaphore с помощью Docker Compose

- name: Создание директории для Docker Compose файла
  file:
    path: /opt/semaphore
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: yes

- name: Копирование Docker Compose файла
  template:
    src: docker-compose.yml.j2
    dest: /opt/semaphore/compose.yml
    owner: root
    group: root
    mode: '0644'
  become: yes

- name: Запуск контейнеров с помощью Docker Compose
  shell: docker compose up -d
  args:
    chdir: /opt/semaphore
  become: yes
