---
#Установка aptitude (опционально, если требуется)
- name: Install aptitude
  apt:
    name: aptitude
    state: latest
    update_cache: true
  become: true

# Установка необходимых системных пакетов
- name: Install required system packages
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
    state: latest
    update_cache: true
  become: true

# Добавление GPG ключа Docker
- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: true

# Добавление репозитория Docker
- name: Add Docker Repository
  apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
  become: true

# Обновление кэша apt и установка docker-ce
- name: Update apt cache and install docker-ce
  apt:
    name: docker-ce
    state: latest
    update_cache: true
  become: true

# Установка модуля Docker для Python
- name: Install Docker Module for Python
  apt:
    name: python3-docker
    state: present
  become: true
